######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 20 15:29:31 2013
######################################################################

TEMPLATE = app
TARGET = sign
DEPENDPATH += .
INCLUDEPATH += .

QT += webenginewidgets widgets sql core
#QT += widgets sql core

# Input
SOURCES += main.cpp \
           mainwindow.cpp

HEADERS += mainwindow.h
     
FORMS += formbase.ui
# 
