######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 20 15:29:31 2013
######################################################################

TEMPLATE = app
TARGET = sign
DEPENDPATH += .
INCLUDEPATH += .

QT += webkit

# Input
SOURCES += database.cpp \ 
          main.cpp \
          mainwindow.cpp

HEADERS += database.h \
          mainwindow.h
     
FORMS += formbase.ui

QT += sql